### ISSUE TITLE
Default Sketch

### ISSUE THREAD

**Issue by gabebear** [Programmable-Air/Code#14]
I got my Programmable-Air and my kids and I are really enjoying making things.

We started playing with just the original default sketch that came pre-programmed which had each button mapped to it's nearest pump/valve and the neopixels mapped to the pressure.

This original sketch would be nice to have as example code.

**Comment by tinkrmind** [comment]
Yay! I'm glad you are enjoying the kit!

And thanks for the request. I'd been meaning to do this for a while and this really made me stop being lazy and just do it! The changes should be reflected in the Arduino library as well.

**Comment by gabebear** [comment]
Thanks for doing this so fast!

I'm using https://create.arduino.cc/editor on a Chromebook right now which is still using version 1.0.4. I'll try this out tomorrow(I think the online editor will have updated to the latest ProgrammableAir library at that point).
