### ISSUE TITLE
Remove unneeded directories in examples

### ISSUE THREAD

**Issue by gabebear** [Programmable-Air/Code#15]
Every example is in it's own directory that contains a single file of the same name. e.g. `Code/examples/catterpillarCode/catterpillarCode.ino`

It would be nice if these were not all nested extra levels. e.g. `Code/examples/catterpillarCode.ino`

This is a small nit, but makes looking through the examples a bit slower(especially if you are browsing files on Github's web interface which isn't the best.)

**Comment by tinkrmind** [comment]
I know it's a bit annoying, but it's the format needed by Arduino, I believe. This repo is also used to manage the Programmable-Air library that shows up in Arduino software's managed libraries.
