### ISSUE TITLE
Figure out a way to add library to Arduino repo directly or via external json source. 

### ISSUE THREAD

**Issue by tinkrmind** [Programmable-Air/Code#5]

**Comment by per1234** [comment]
Do you mean that you want to allow [installation via the Arduino IDE's Library Manager](https://www.arduino.cc/en/Guide/Libraries#toc3)?

If so, these are the things that need to be done:
- Move library to the root of the repository.
- Add a library.properties file that complies with the Arduino Library Specification: https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format
- Create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.
- Open an issue report at https://github.com/arduino/Arduino/issues requesting addition to the Arduino Library Manager index.

More information:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by tinkrmind** [comment]
Thanks so much! I will do this as soon as I rewrite the library to conform to the Arduino styleguide.
